package airport.enums;
public enum BaggageStatus { CHECKED_IN, WAITING_FOR_SECURITY, IN_SECURITY, SECURITY_CLEARED, SECURITY_REJECTED, WAITING_FOR_SORTING, SORTED, WAITING_FOR_LOADING, LOADING, LOADED, DELAYED }
