package airport;
import airport.model.*; import airport.persistence.*; import airport.simulation.*; import java.util.*;
public class Main {
 private static final Scanner sc=new Scanner(System.in);
 public static void main(String[]args){DatabaseManager.initialize();JdbcRepository repo=new JdbcRepository();Airport airport=new Airport(repo);demo(airport);while(true){menu();String c=sc.nextLine().trim();switch(c){case"1"->airport.showFlights();case"2"->airport.showBaggage();case"3"->new SimulationEngine(new ArrayList<>(airport.getFlights()),new ArrayList<>(airport.getBaggage()),repo).run();case"4"->track(airport,repo);case"5"->addFlight(airport);case"6"->addBag(airport);case"7"-> {System.out.println("Goodbye.");return;}default->System.out.println("Invalid choice.");}}}
 static void menu(){System.out.println("\n==============================================\n      AIRPORT BAGGAGE HANDLING SIMULATOR\n==============================================\n1. View Flights\n2. View Baggage\n3. Start Concurrent Simulation\n4. Track Baggage History\n5. Add Flight\n6. Add Baggage\n7. Exit\n==============================================\nEnter choice:");}
 static void demo(Airport a){Flight f1=new Flight("AI205","Delhi",8),f2=new Flight("6E412","Mumbai",7),f3=new Flight("UK901","Bengaluru",6);a.addFlight(f1);a.addFlight(f2);a.addFlight(f3);String[] names={"Rahul","Ananya","Vikram","Neha","Arjun","Meera","Kabir","Isha","Rohan","Diya","Aditya","Sneha"};double[] w={18,20,15,42,22,16,14,19,21,17,13,23};for(int i=0;i<names.length;i++){Passenger p=new Passenger(String.format("P%03d",i+1),names[i]);a.addPassenger(p);Flight f=i%3==0?f1:i%3==1?f2:f3;Baggage b=switch(i%4){case 0->new StandardBaggage("B"+(101+i),p,f,w[i]);case 1->new FragileBaggage("B"+(101+i),p,f,w[i]);case 2->new PriorityBaggage("B"+(101+i),p,f,w[i]);default->new OversizedBaggage("B"+(101+i),p,f,w[i]);};try{a.addBaggage(b);}catch(Exception e){System.out.println(e.getMessage());}}}
 static void track(Airport a,JdbcRepository r){System.out.print("Baggage ID: ");String id=sc.nextLine().trim();boolean ok=a.getBaggage().stream().anyMatch(b->b.getBagId().equalsIgnoreCase(id));if(ok)r.printHistory(id);else System.out.println("Baggage not found.");}
 static void addFlight(Airport a){try{System.out.print("Flight number: ");String n=sc.nextLine();System.out.print("Destination: ");String d=sc.nextLine();System.out.print("Baggage capacity: ");int c=Integer.parseInt(sc.nextLine());a.addFlight(new Flight(n,d,c));System.out.println("Flight added.");}catch(Exception e){System.out.println("Invalid input: "+e.getMessage());}}
 static void addBag(Airport a){try{System.out.print("Bag ID: ");String id=sc.nextLine();System.out.print("Passenger ID: ");String pid=sc.nextLine();System.out.print("Passenger name: ");String name=sc.nextLine();System.out.print("Flight number: ");String fn=sc.nextLine();Flight f=a.getFlight(fn);if(f==null){System.out.println("Flight not found.");return;}System.out.print("Weight: ");double w=Double.parseDouble(sc.nextLine());System.out.println("Type: 1 Standard  2 Fragile  3 Priority  4 Oversized");int t=Integer.parseInt(sc.nextLine());Passenger p=new Passenger(pid,name);a.addPassenger(p);Baggage b=switch(t){case 1->new StandardBaggage(id,p,f,w);case 2->new FragileBaggage(id,p,f,w);case 3->new PriorityBaggage(id,p,f,w);case 4->new OversizedBaggage(id,p,f,w);default->null;};if(b==null){System.out.println("Invalid type.");return;}a.addBaggage(b);System.out.println("Baggage registered.");}catch(Exception e){System.out.println("Could not register baggage: "+e.getMessage());}}
}
